# -*- coding: utf-8 -*-
"""CUDA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wDryKrvP85hIblKvZ3lkyoz2oHMiI9vb
"""

!/usr/local/cuda/bin/nvcc --version

# Commented out IPython magic to ensure Python compatibility.
!pip install git+git://github.com/andreinechaev/nvcc4jupyter.git
# %load_ext nvcc_plugin

!git clone https://github.com/NVIDIA/cuda-samples/
!cp cuda-samples/Common/* /usr/local/include

# Commented out IPython magic to ensure Python compatibility.
# %%cu
# #include <iostream>
# __global__ void helloFromGPU(){
#     printf("GPU¥n");
# }
# 
# int main(void){
#     std::cout<<"CPU\n";
#     helloFromGPU<<<1,10>>>();
# }

# Commented out IPython magic to ensure Python compatibility.
# %%cu
# #include <iostream>
# int main() {
#     std::cout << "Hello world\n";
#     return 0;
# }

# Commented out IPython magic to ensure Python compatibility.
!pip install git+git://github.com/andreinechaev/nvcc4jupyter.git
# %load_ext nvcc_plugin

# Commented out IPython magic to ensure Python compatibility.
# %%cu
# 
# #include <iostream>
# __global__ void helloFromGPU(){
#     printf("from GPU thread %d\n",threadIdx.x);
# }
# 
# int main(void){
#     std::cout<<"CPU\n";
#     helloFromGPU<<<1,1>>>();
#     cudaDeviceSynchronize();
# }

# Commented out IPython magic to ensure Python compatibility.
# %%cu
# 
#

